name: CMake

on:
  push:
    branches:
      - 'main'
      - 'develop'
    tags:
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build_linux:
    name: Build on linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Conan install and usage
      - run: |
          pip3 install conan
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan install ${{github.workspace}}/conan/conanfile.txt --install-folder=${{github.workspace}}/deps --build=missing

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  # conan profile update settings.compiler.cppstd=17 default
  build_macos:
    name: Build on macOS
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - name: Conan install and usage
      - run: |
          pip3 install conan
          conan profile new default --detect
          conan install ${{github.workspace}}/conan/conanfile.txt --install-folder=${{github.workspace}}/deps --build=missing

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  build_windows:
    name: Build on Windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Conan install and usage
      - run: |
          pip3 install conan
          conan profile new default --detect
          conan profile update settings.compiler.runtime=MD default
          conan install ${{github.workspace}}/conan/conanfile.txt --install-folder=${{github.workspace}}/deps --build=missing

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

#  test:
#    steps:
#      - name: Test
#        working-directory: ${{github.workspace}}/build
#        # Execute tests defined by the CMake configuration.
#        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
#        run: ctest -C ${{env.BUILD_TYPE}}
